### ISSUE TITLE
苍天大地啊，大佬别乱改事件参数啊

### ISSUE THREAD

**Issue by guliang21** [yhuse/SunnyUI#17]
UIComboBox 的 KeyPress 事件，sender 参数居然不是 UIComboBox 而是一个 TextBox

这完全就改变了事件定义的方式了，整个参数就废掉了。

**Comment by yhuse** [comment]
你先看看UIComboBox的代码，看看UIComboBox是怎么实现的，不是改的，而是KeyPress 没有放出来
