### ISSUE TITLE
建议部分UI功能可改进

### ISSUE THREAD

**Issue by ZehuanZhang** [yhuse/SunnyUI#2]
例如窗体Header，只支持移动，但双击最大化、移至屏幕顶部最大化，最大化后拖动header恢复原大小的功能目前好像都不支持，实际使用还是挺影响体验的

**Comment by yhuse** [comment]
是的，因为相应拖动事件后，相应不了双击事件，一直没解决

**Comment by ZehuanZhang** [comment]
我尝试重写C#自带的事件，暂时性的解决了这个问题，但缺点是没有直接使用API，可能有一定的性能差异，但是在我电脑上测试不出来到底多少差别，关于这个做了一个pull request，如果该方法带来的开支不大，也是一种可行的方案（当然目前好像发现一些小问题，比如还没有针对窗体的可调整大小属性进行判断，但这些可以后期慢慢修复）。
另外，自定义的borderless form存在没有Windows Aero的阴影特效问题，我尝试使用了一些方法（Windows API或窗体叠加），但是多少都有些问题，因此没有做push和pr。因为我主要做通用平台的底层计算开发，不是很了解Windows API，这一块如果您了解的话可以考虑稍微加强。

**Comment by yhuse** [comment]
我先看下代码，测试下可行性，合适的话会合并，谢谢您的支持！~

**Comment by yhuse** [comment]
我这是自己重写了窗体标题栏，要真正和原生的一样，需要从底层重绘

**Comment by ZehuanZhang** [comment]
其实对这个项目挺感兴趣的，因为我做的主要是专业计算的核心部分，但是偶尔也需要做界面，WinForm的自带控件中规中矩，说不上好看，甚至有时候用起来还很难受，之前我也调研过，不少做的好看的winform控件库都是收费的（且很昂贵），若能有机会参与开发这个控件库也是很幸运的。

我之前提交的pr中，UIForm.cs第477行的代码逻辑有点小问题，应该将其放到判断语句结束后。

非常感谢您将如此有意义的项目开源，希望能够参与并学习到更多有用的知识！
