### ISSUE TITLE
问一下关于开源协议的问题

### ISSUE THREAD

**Issue by HengzheLi** [yhuse/SunnyUI#23]
您好  商业应用授权吗  GPL的协议不敢直接用T_T

**Comment by yhuse** [comment]
商用需要授权，取得商用授权后可以商用。



---原始邮件---
发件人: "hectorli"<notifications@github.com&gt;
发送时间: 2020年12月27日(周日) 上午10:31
收件人: "yhuse/SunnyUI"<SunnyUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [yhuse/SunnyUI] 问一下关于开源协议的问题 (#23)




 
您好  商业应用授权吗  GPL的协议不敢直接用T_T
