### ISSUE TITLE
Symbol&RadiusSides 这两个属性在属性界面无法修改

### ISSUE THREAD

**Issue by Goleven** [yhuse/SunnyUI#24]
![image](https://user-images.githubusercontent.com/34236843/103874643-6754cc00-510c-11eb-8d79-9a96c367c7b3.png)

我是从Nuget上下载的, 版本是 3.0.0

**Comment by yhuse** [comment]
.net 5 的winform控件是有这个问题，解决中。。。

**Comment by yhuse** [comment]
.net 5的属性编辑器问题还得微软解决。
