### ISSUE TITLE
将Form窗口设置为控件放入Panel，位置偏移。

### ISSUE THREAD

**Issue by PRZX** [yhuse/SunnyUI#25]
使用SunnyUI3.0,将Form窗口设置为控件放入UIPanel时，在设置为控件的Form窗口放上后在UIPanel上显示时，位置出现偏移。

**Comment by yhuse** [comment]
参考Demo，使用UIPage



---原始邮件---
发件人: "PRZX"<notifications@github.com&gt;
发送时间: 2021年1月9日(周六) 晚上6:56
收件人: "yhuse/SunnyUI"<SunnyUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [yhuse/SunnyUI] 将Form窗口设置为控件放入Panel，位置偏移。 (#25)




 
使用SunnyUI3.0,将Form窗口设置为控件放入UIPanel时，在设置为控件的Form窗口放上后在UIPanel上显示时，位置出现偏移。
