### ISSUE TITLE
窗体图标无法设置，从任务栏上看依然为默认图标，SunnyUI.Demo也是如此

### ISSUE THREAD

**Issue by TscCai** [yhuse/SunnyUI#26]
主窗体为AsideMainFrame，设置了Icon属性，运行后在任务栏的缩略图上看到图标还是默认图标。

**Comment by yhuse** [comment]
ShowIcon=true，如果标题栏不需要显示，则设置ShowTitleIcon=false

**Comment by TscCai** [comment]
整个SunnyUI项目未见ShowTitleIcon属性，是否为3.0新特性？
![1](https://user-images.githubusercontent.com/9205914/105570032-8fd1fc80-5d81-11eb-948b-375eb309748b.png)
![2](https://user-images.githubusercontent.com/9205914/105570034-91032980-5d81-11eb-8657-9983ea293251.png)
