### ISSUE TITLE
窗口大尺寸图标存在BUG

### ISSUE THREAD

**Issue by TscCai** [yhuse/SunnyUI#30]
当给UIAsideMainFrame（推测应该只要是UIFrame及其子类，均存在该问题）的Icon设置一个仅包含256x256的.ico图标时，会在UIForm.cs的860行左右（OnPaint()方法内）报数组越界的错误，导致窗体无法绘制，程序不能运行。
```cs
if (ShowIcon && Icon != null)
{
    e.Graphics.DrawImage(Icon.ToBitmap(), 6, (TitleHeight - 24) / 2, 24, 24);
}
```
但如果该.ico文件是一个包含多个尺寸的图标文件，例如：我使用了包含48x48,64x64,128x128,256x256的.ico文件，48x48在最末尾，那么这里base.Icon的尺寸即为48x48，不会报错。
在原生的Windows.Form中，即使单使用256的图标也不会有问题，反编译了一下代码看了看，在绘制图标时会放缩图标，故未报错。

**Comment by yhuse** [comment]
已修正
