### ISSUE TITLE
ChartForm Bug 

### ISSUE THREAD

**Issue by SAGERAS666** [yhuse/SunnyUI#31]
1）ChartForm在只存在单个数据的时候，会发生异常，源于其内部的一个判断；
2）某些情况下，ChartForm会由于计算X轴时间而发生异常，定位源码，修改如下：
源码内部之前的写法是return new DateTimeInt64(new DateTime(year, month, day+direction, 0, 0, 0)).DoubleValue;
有时候day值会为31号，如果再加上deriction则会报错。

switch (_scaleLevel)
            {
                default:
                    if (direction == 1 && month == 1 && day == 1 && hour == 0 && minute == 0 && second == 0)
                        return date;
                    else
                        return new DateTimeInt64(new DateTime(year, 1, 1, 0, 0, 0).AddYears(direction)).DoubleValue;

                case UIDateScaleLevel.Month:
                    if (direction == 1 && day == 1 && hour == 0 && minute == 0 && second == 0)
                        return date;
                    else
                        return new DateTimeInt64(new DateTime(year, month, 1, 0, 0, 0).AddMonths(direction)).DoubleValue;

                case UIDateScaleLevel.Day:
                    if (direction == 1 && hour == 0 && minute == 0 && second == 0)
                        return date;
                    else
                        return new DateTimeInt64(new DateTime(year, month, day, 0, 0, 0).AddDays(direction)).DoubleValue;    
                    
                case UIDateScaleLevel.Hour:
                    if (direction == 1 && minute == 0 && second == 0)
                        return date;
                    else
                        return new DateTimeInt64(new DateTime(year, month, day, hour, 0, 0).AddHours(direction)).DoubleValue;

                case UIDateScaleLevel.Minute:
                    if (direction == 1 && second == 0)
                        return date;
                    else
                        return new DateTimeInt64(new DateTime(year, month, day, hour, minute, 0).AddMinutes(direction)).DoubleValue;

                case UIDateScaleLevel.Second:
                    return new DateTimeInt64(new DateTime(year, month, day, hour, minute, second).AddSeconds(direction)).DoubleValue;

                case UIDateScaleLevel.Millisecond:
                    return new DateTimeInt64(new DateTime(year, month, day, hour, minute, second, millisecond).AddMilliseconds(direction)).DoubleValue;
            }

**Comment by yhuse** [comment]
这个我已经改过了，Gitee应该已经更新了，github可能没更新



---Original---
