### ISSUE TITLE
Symbol：字体图标 右边没有按钮？

### ISSUE THREAD

**Issue by dockerliu** [yhuse/SunnyUI#47]
你好，设置UISymbolButton和UISymbolLabel的属性：
Symbol：字体图标 右边没有按钮？想改一下图标，没法改，请问我这是哪里设置有问题吗？

![image](https://user-images.githubusercontent.com/57223447/163605520-b4a83fda-16e3-4ce7-bcbe-a21224a98f32.png)

**Comment by yhuse** [comment]
加群，看群公告常见问题答疑





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月16日(周六) 凌晨2:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yhuse/SunnyUI] Symbol：字体图标 右边没有按钮？ (Issue #47)




 
你好，设置UISymbolButton和UISymbolLabel的属性：
 Symbol：字体图标 右边没有按钮？想改一下图标，没法改，请问我这是哪里设置有问题吗？

**Comment by xuan2261** [comment]
> 加群，看群公告常见问题答疑
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年4月16日(周六) 凌晨2:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [yhuse/SunnyUI] Symbol：字体图标 右边没有按钮？ (Issue #47) 你好，设置UISymbolButton和UISymbolLabel的属性： Symbol：字体图标 右边没有按钮？想改一下图标，没法改，请问我这是哪里设置有问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Hi admin. I know a lot of people who can't join the group chat because they can't create or don't have a QQ chat account. Can you create a group on discord or telegram so that everyone can exchange more conveniently? I think a lot of people will like this.

**Comment by yhuse** [comment]
VS的Bug，将项目从.Net5或着.Net6改为.Net Framework即可。
