### ISSUE TITLE
Yes, code has been refactored, it has been hidden。

### ISSUE THREAD

**Issue by fatkulamri** [yhuse/SunnyUI#51]
Yes, code has been refactored, it has been hidden。

_Originally posted by @yhuse in https://github.com/yhuse/SunnyUI/issues/48#issuecomment-1102663131_

**Comment by fatkulamri** [comment]
I think this feature very important to create menu with NavMenuItem, so we can set Symbol, Tag, etc.

After it has hidden, we cannot set Symbol, Tag, etc from code like before.

![image](https://user-images.githubusercontent.com/1744057/164199710-4b4cc544-a6b7-4ec0-9469-ee9c006823ad.png)

**Comment by yhuse** [comment]
UINavMenu - SetNodeSymbol
