### ISSUE TITLE
BarChart的纵坐标轴显示问题请教

### ISSUE THREAD

**Issue by 18205097282** [yhuse/SunnyUI#58]
![image](https://user-images.githubusercontent.com/53631755/188779435-11c7ce84-940e-434e-b8f2-f12ec2980183.png)

1.请问如何自定义纵坐标轴的显示数值的小数点位数  （option.YAxis.AxisLabel.DecimalCount 这个参数不起作用)

2.请问如何取消纵坐标轴的这些虚线  ( option.YAxis.ShowGridLine = true  不起作用)
![image](https://user-images.githubusercontent.com/53631755/188779676-b7eb47d0-fe6d-4f2e-ba40-7806696853cd.png)

3.当Y轴数值过大时，会超出图表的显示范围，请问如何解决
![image](https://user-images.githubusercontent.com/53631755/188779839-9e0e9759-2869-4b9b-9094-3859bc61277d.png)

**Comment by yhuse** [comment]
1、最新版都已经归集到坐标轴的DecimalPlaces
2、暂时无法关闭
3、Option.Grid.Left
