### ISSUE TITLE
Problem ui form in .NET 6

### ISSUE THREAD

**Issue by boolinux** [yhuse/SunnyUI#59]
![image](https://user-images.githubusercontent.com/38902725/193482874-fcdb27a7-bfdf-4aa8-82b6-d886d4af844d.png)

i can't resize form if i change to UIPage. uiDataGridview dock fill, not ignore uiDataGridViewFooter and uiPagination

**Comment by yhuse** [comment]
.Net6的问题，不过不影响使用。建议换回.NetFramework
