### ISSUE TITLE
SunnyUI 3.3.0版本   CheckBoxGroup  item的字体颜色无法改变 只能黑色

### ISSUE THREAD

**Issue by 18205097282** [yhuse/SunnyUI#62]
![image](https://user-images.githubusercontent.com/53631755/206328847-50626803-d4cb-4bf4-a46d-ea71548361ed.png)
![image](https://user-images.githubusercontent.com/53631755/206328865-eef544c7-809e-49df-9b2e-e92e030a27f4.png)
ForeColor 只能改变Title的颜色  而无法改变 选择项的字体

**Comment by yhuse** [comment]
更新到最新
