### ISSUE TITLE
SunnyUI 3.3.1 UIComboDataGridView 搜索按钮，清除按钮没有设置多语言

### ISSUE THREAD

**Issue by wangxvhu** [yhuse/SunnyUI#63]
UIComboDataGridView 搜索按钮，清除按钮没有设置多语言。
<img width="283" alt="Screenshot 2023-01-17 175452" src="https://user-images.githubusercontent.com/37278632/212866945-747183a2-2bc2-4d10-87f2-cd44c1dbb659.png">

**Comment by yhuse** [comment]
已更新
