### ISSUE TITLE
GroupBox error when combined with Sunny Button

### ISSUE THREAD

**Issue by hautlym** [yhuse/SunnyUI#68]
I am using Sunny Ui version 3.3.4.0 and .NET 6
When I use the GroupBox in combination with the library buttons. After reloading the form or building the project, the color of the buttons is set to the default state. When using the default winform button, this error does not occur. This state also happens with the background color of the DatagridView
Even though I checked in git change in visual studio 2022 it still doesn't catch this change

**Comment by yhuse** [comment]
StyleCustomMode = true




Sunny
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhuse/SunnyUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 中午12:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yhuse/SunnyUI] GroupBox error when combined with Sunny Button (Issue #68)





 
I am using Sunny Ui version 3.3.4.0 and .NET 6
 When I use the GroupBox in combination with the buttons of the . After reloading the form or building the project, the color of the buttons is set to the default state. When using the default winform button, this error does not occur. This state also happens with the background color of the DatagridView
 Even though I checked in git change in visual studio 2022 it still doesn't catch this change

**Comment by hautlym** [comment]
> StyleCustomMode = true Nắng ***@***.***  
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "yhuse/SunnyUI" *** @***.***>;发送时间: 2023年4月10日(星期一) 中午12:53 ***@***.***>; ***@***.***>; Lưu ý: [yhuse/SunnyUI] Lỗi GroupBox khi kết hợp với Nút Sunny (Số [68](https://github.com/yhuse/SunnyUI/issues/68) ) Tôi đang sử dụng Sunny Ui phiên bản 3.3.4.0 và .NET 6 Khi tôi sử dụng GroupBox kết hợp với các nút của . Sau khi tải lại biểu mẫu hoặc xây dựng dự án, màu của các nút được đặt thành trạng thái mặc định. Khi sử dụng nút winform mặc định thì không xảy ra lỗi này. Trạng thái này cũng xảy ra với màu nền của DatagridView. Mặc dù tôi đã kiểm tra git change trong visual studio 2022 nhưng vẫn không nhận được sự thay đổi này — Trả lời trực tiếp email này, xem trên GitHub hoặc hủy đăng ký.Bạn đã nhận được thông báo này vì bạn đã đăng ký chuỗi này. Tin nhắn ID: ***@***.***>

16 / 5.000
Kết quả dịch
Kết quả bản dịch
Thank you very much

**Comment by hautlym** [comment]
Thank you very much

> StyleCustomMode = true Nắng ***@***.***  
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "yhuse/SunnyUI" *** @***.***>;发送时间: 2023年4月10日(星期一) 中午12:53 ***@***.***>; ***@***.***>; Lưu ý: [yhuse/SunnyUI] Lỗi GroupBox khi kết hợp với Nút Sunny (Số [68](https://github.com/yhuse/SunnyUI/issues/68) ) Tôi đang sử dụng Sunny Ui phiên bản 3.3.4.0 và .NET 6 Khi tôi sử dụng GroupBox kết hợp với các nút của . Sau khi tải lại biểu mẫu hoặc xây dựng dự án, màu của các nút được đặt thành trạng thái mặc định. Khi sử dụng nút winform mặc định thì không xảy ra lỗi này. Trạng thái này cũng xảy ra với màu nền của DatagridView. Mặc dù tôi đã kiểm tra git change trong visual studio 2022 nhưng vẫn không nhận được sự thay đổi này — Trả lời trực tiếp email này, xem trên GitHub hoặc hủy đăng ký.Bạn đã nhận được thông báo này vì bạn đã đăng ký chuỗi này. Tin nhắn ID: ***@***.***>
