### ISSUE TITLE
支持多选的 Combobox

### ISSUE THREAD

**Issue by guliang21** [yhuse/SunnyUI#7]
做不到大佬这么漂亮，只好来求大佬了。可以增加一个支持多选的 Combobox 吗

还有一个功能，我做了 2 天也没实现，DataGridViewLinkColumn 只支持一个 Link，如果有编辑、删除，就只能用 2 个 Column 了，很挫。本来是想重新绘的，一个 Column 中有两个 Link，弄到最后发现，这样不好做权限控制，最好的做法还是实现 列头合并。

现在做 Winform UI 的真的太少太少了，支持大佬！

**Comment by yhuse** [comment]
已经有了
