### ISSUE TITLE
ShowSuccessTip 重复弹出会报错

### ISSUE THREAD

**Issue by yiningzeng** [yhuse/SunnyUI#71]
连到系统上的设备没有发挥作用。
   在 Sunny.UI.LayeredWindow.Update()
   在 Sunny.UI.UIMessageTip.<>c__DisplayClass39_0.<layer_Showing>b__0(Object arg)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart(Object obj)
System.ComponentModel.Win32Exception (0x80004005): 连到系统上的设备没有发挥作用。
   在 Sunny.UI.LayeredWindow.Update()
   在 Sunny.UI.UIMessageTip.<>c__DisplayClass39_0.<layer_Showing>b__0(Object arg)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by yhuse** [comment]
用窗体主线程调用
