### ISSUE TITLE
什么时候可以支持rider的设计器呢？

### ISSUE THREAD

**Issue by rtb4** [yhuse/SunnyUI#76]
rider设计器会报错如图，我确定rider引用以及dll存放位置都是正确的。
![QQ截图20240112232441](https://github.com/yhuse/SunnyUI/assets/89714376/47d103d3-6e81-49d4-bf9e-0475872a8b5e)

但是VSz正常
![QQ截图20240112232511](https://github.com/yhuse/SunnyUI/assets/89714376/d7f39cb8-106f-4b82-ad4c-58266c2acb9c)

**Comment by yhuse** [comment]
请用VS
