### ISSUE TITLE
VS2019 .Net 4.7.2 窗口标题栏无法显示icon图标问题

### ISSUE THREAD

**Issue by tbplayer1989** [yhuse/SunnyUI#79]
环境：VS2019 .net4.7.2 winform
问题：无论使用UIForm或UIForm2类，设置icon属性并设置showIcon为true，但是标题栏图标不显示，使用实例代码运行时也存在相同问题，请问一下是哪里的问题，感谢。

**Comment by tbplayer1989** [comment]
操作系统：win10

**Comment by yhuse** [comment]
ShowTitleIcon
