### ISSUE TITLE
UIPanel、UICheckBoxGroup 边框设置透明后，运行依然显示边框

### ISSUE THREAD

**Issue by guliang21** [yhuse/SunnyUI#8]
如题，在 UIEditForm 里

**Comment by yhuse** [comment]
https://www.cnblogs.com/yhuse/p/SunnyUI_Style.html

RectSides：边框显示方向
无：不显示边框
全部：显示全部边框
顶：显示顶部边框
底：显示底部边框
左：显示左侧边框
右：显示右侧边框
注：边框显示和圆角设置相关，如果一侧的边框两端端点为圆角，则此边框必定显示。
