### ISSUE TITLE
ComboBox Text alignment center not working. Please help!

### ISSUE THREAD

**Issue by nghiakthp2401** [yhuse/SunnyUI#82]
![image](https://github.com/yhuse/SunnyUI/assets/135792797/a27f4ad2-7a35-43fd-88e4-36181c564a2c)

**Comment by nghiakthp2401** [comment]
![image](https://github.com/yhuse/SunnyUI/assets/135792797/53838dfd-60e4-41d4-bc37-e35ce6b5c650)

**Comment by yhuse** [comment]
ComboBox Text alignment just left show
