### ISSUE TITLE
请问一下，UITabControl顶部的TabPage右侧 是否可以设置预留位置？

### ISSUE THREAD

**Issue by SuperRope** [yhuse/SunnyUI#83]
鄙人手拙，画了个草图，看下是否明白，右边红色框是预留的位置
Tips：上面的tabpage，会动态添加，可能会存在超出title范围的情况。所以不能直接放UITabControl到顶部Title的位置
![image](https://github.com/yhuse/SunnyUI/assets/51290888/eb3369c8-565f-4d30-b7c7-d585d82fda73)

**Comment by yhuse** [comment]
TabPage不多的话，可以在这个位置放三个按钮。

**Comment by SuperRope** [comment]
> TabPage不多的话，可以在这个位置放三个按钮。

比较多哦，动态添加tabpages，可能会存在遮挡覆盖的情况，想要做的效果，就类似浏览器顶部右上角 有一点预留位置即可
