### ISSUE TITLE
UIForm调整窗体大小组件会闪烁

### ISSUE THREAD

**Issue by Rozayu** [yhuse/SunnyUI#85]
操作系统：win10；内存：24G 2666MHz；CPU：i5-10500；.NET框架：4.7.2；
IDE新建窗体后，修改Form继承为UIForm，随便添加几个控件，然后调整窗体的Resizable属性为true，运行后调整窗体大小，其中的控件会在透明状态和正常状态之间闪烁。
![image](https://github.com/user-attachments/assets/4b22930f-d47c-48c0-8aff-6f8b01625b11)

**Comment by yhuse** [comment]
检查PC是否有加密软件这类的，会引起VS编程环境的问题，与SunnyUI控件无关。
