### ISSUE TITLE
UITextBox handles neither GotFocus nor Enter Events.

### ISSUE THREAD

**Issue by charset** [yhuse/SunnyUI#9]
SunnyUI 版本2.2.6.0
无法实现当UITextBox控件获得焦点的时候，自动将文字选中的功能。
……
//controls[i].GotFocus += CommonFocusHandler; 
controls[i].Enter += CommonFocusHandler;
……
private void CommonFocusHandler(object sender, EventArgs args) {
            UITextBox edit = sender as UITextBox;
            if (!string.IsNullOrEmpty(edit?.Text)) {
                 edit?.SelectAll();
                //edit.Select(0, edit.Text.Length);
            }
        }
CommonFocusHandler无论如何都不会进入。

**Comment by charset** [comment]
是否是这里的问题？UIEdit.cs 474行附近。
        /// <summary>
        ///     在得到焦点时修改文体框的背景色
        /// </summary>
        /// <param name="e"></param>
        protected override void OnGotFocus(EventArgs e)
        {
            base.OnGotFocus(e);
            SelectionStart = Text.Length;
            SelectionLength = 0;
        }

**Comment by yhuse** [comment]
已解决
